xwp/wp-customize-posts

php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php
Reported by mac2net at https://wordpress.org/support/topic/cant-get-this-working-1
=> Change method for registering scripts/styles to fix conflict w/ Jetpack

css/customize-posts.css, php/class-wp-customize-posts.php
Ensures that the link modal, autocomplete, inline toolbar, and other elements in the editor can appear.
Makes sure that the editor integration works when `widgets` component is filtered to be disabled in the Customizer (not that anyone should ever do this :wink:)
=> Harden editor

php/class-wp-customize-posts.php
Let a post type by default only be displayed in the Customizer if `show_ui` and `publicly_queryable` are true. Let this be overridden if `show_in_customizer` is defined.
=> Add show_in_customizer option for register_post_type()

php/class-wp-customize-posts-preview.php
I encountered two warnings on a basic environment, which I fixed with some extra conditionals.
Warning: array_keys() expects parameter 1 to be array, null given in
/wp-content/plugins/customize-posts/php/class-w
p-customize-posts-preview.php on line 150
Warning: Invalid argument supplied for foreach() in
/wp-content/plugins/customize-posts/php/class-w
p-customize-posts-preview.php on line 156
=> Fix handling the discovery of postmeta settings for posts that lack any postmeta

php/class-wp-customize-post-setting.php, php/class-wp-customize-postmeta-setting.php, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts.php
Customize Posts is not working with Customize Snapshots.
I found that post and postmeta changes were not applied on the frontend when the UUID was supplied. This was due to the preview filters being added in the `customize_preview_init` action as opposed to being added whenever a setting's `preview()` method was called.
I also found that even with this fixed, the settings would not apply on the frontend for users who were not authenticated. There were a lot of capability checks added for _previewing_ settings which I now believe to be an error.
=> Fix compatibility with Customize Snapshots

css/customize-posts.css, js/customize-post-section.js
I also added a little JS to click the active mce button and close the link popup if it's open when you click the "Close Editor" button. That way it reverts to the original state when you close the editor.
Fixes #80
=> Fix media buttons

js/customize-controls-patched-36521.js, js/customize-featured-image.js, js/customize-page-template.js, js/customize-post-section.js, js/customize-preview-featured-image.js, js/edit-post-preview-admin-featured-image.js, js/edit-post-preview-admin-page-template.js, php/class-customize-posts-plugin.php, php/class-edit-post-preview.php, php/class-wp-customize-featured-image-controller.php, php/class-wp-customize-page-template-controller.php, php/class-wp-customize-post-field-partial.php, php/class-wp-customize-postmeta-controller.php, php/class-wp-customize-postmeta-setting.php, tests/php/test-class-edit-post-preview.php, tests/php/test-class-wp-customize-featured-image-controller.php, tests/php/test-class-wp-customize-page-template-controller.php, tests/php/test-class-wp-customize-postmeta-controller.php, tests/php/test-class-wp-customize-posts-preview.php
=> Add support for featured image

css/customize-posts.css
@westonruter I know it's bad to use !important, however in this case doing so resolves a lot of issues that are encountered. Also note that we cannot assume the end user wouldn't have plugins like TinyMCE Advanced installed. I've installed that particular plugin and tested the below and it works 100% without any issues. 
I'm open to alternative ways to achieve the end goal of the code below.
=> Add z-index for mce-floatpanel and mce-tooltip

css/customize-posts.css, php/class-customize-posts-plugin.php
By adding `autosave` as a dependency to the `customize-posts` JS the editor tabs and media button becomes functional again.
This suppresses `customize.php?return=%2Fwp-admin%2Fprofile.php:4243Uncaught TypeError: Cannot read property 'interval' of undefined`
I've also added some styles to improve the editor in mobile.
Fixes #90, and fixes #45
=> Fix JS error

php/class-wp-customize-posts-preview.php
I noticed a PHP notice raised when adding a nav menu item in the Customizer. The notice was generated in `\WP_Customize_Posts_Preview::filter_get_post_meta_to_add_dynamic_postmeta_settings()`. The post ID being passed into this filter is the placeholder (negative) post ID representing a not-yet-inserted `nav_menu_item` post. Nevertheless, in spite of the nav menu item having a negative post ID, it actually gets passed in as an absolute value (`6691070724235418000 ` instead of `-6691070724235418000`). In either case, the ID gets passed into `get_post()` which would fail since it is not a valid post ID. 
The meta lookup that is resulting in this issue is for the `type_label` item.
Call stack:
```
#0  WP_Customize_Posts_Preview->filter_get_post_meta_to_add_dynamic_postmeta_settings()
#1 …
```
=> Fix PHP notice generated when adding nav menu items

Gruntfile.js, phpcs.ruleset.xml
Depends on https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/560
With this we can get rid of `grunt-checktextdomain`.
=> Define text_domain for i18n sniff

readme.md, readme.txt
There's a notice at https://translate.wordpress.org/projects/wp-plugins/customize-posts
> This plugin is not properly prepared for localization. If you would like to translate this plugin, please contact the author.
I guess it is because we don't have the Text Domain declared.
=> Add missing text domain to plugin meta

js/customize-posts.js, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
Avoids `console.error()` call when suppressing a custom post type from being added as a panel via `show_in_customizer`.
See #128.
=> Export all registered post types to client, but only register panels if show_in_customizer

php/class-customize-posts-plugin.php
This permits filtering of the final URL, which lets me use this plugin as a Git submodule without defining `SCRIPT_DEBUG`
=> Use `plugins_url()` directly

php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts-preview.php
This fixes an issue whereby you add a control for a given postmeta but the control won't appear unless the postmeta is explicitly referenced via a `get_post_meta()` call sine this is when the setting gets added and thus exported from the preview to the pane.
While it could be argued that it is expected behavior for a control to not appear if the postmeta is not referenced in the preview, there may very well be postmeta manipulated for a given post that doesn't appear in the preview since you may be on an archive page.
=> Add all postmeta settings for registered types not just the ones actually referenced

js/customize-post-section.js, js/customize-posts.js, js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php
Placeholder field updates live as title changes.
Fixes #63
=> Add post slug field

js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php
=> Let post_name changes skip doing any partial refreshing by default

.gitignore, css/customize-posts.css, js/customize-post-section.js, js/customize-posts-panel.js, js/customize-posts.js, js/customize-preview-posts.js, js/edit-post-preview-admin.js, php/class-edit-post-preview.php, php/class-wp-customize-dynamic-control.php, php/class-wp-customize-featured-image-controller.php, php/class-wp-customize-page-template-controller.php, php/class-wp-customize-post-discussion-fields-control.php, php/class-wp-customize-post-setting.php, php/class-wp-customize-postmeta-controller.php, php/class-wp-customize-postmeta-setting.php, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php, tests/php/test-ajax-class-wp-customize-posts.php, tests/php/test-class-wp-customize-featured-image-controller.php, tests/php/test-class-wp-customize-page-template-controller.php, tests/php/test-class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-postmeta-controller.php, tests/php/test-class-wp-customize-postmeta-setting.php, tests/php/test-class-wp-customize-posts.php
=> Post Status Control

css/customize-posts.css, js/customize-post-section.js, js/customize-posts-panel.js, js/customize-posts.js, php/class-wp-customize-dynamic-control.php, php/class-wp-customize-featured-image-controller.php, php/class-wp-customize-page-template-controller.php, php/class-wp-customize-post-discussion-fields-control.php, php/class-wp-customize-post-setting.php, php/class-wp-customize-postmeta-controller.php, php/class-wp-customize-postmeta-setting.php, php/class-wp-customize-posts.php, tests/php/test-ajax-class-wp-customize-posts.php, tests/php/test-class-wp-customize-featured-image-controller.php, tests/php/test-class-wp-customize-page-template-controller.php, tests/php/test-class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-postmeta-controller.php, tests/php/test-class-wp-customize-postmeta-setting.php, tests/php/test-class-wp-customize-posts.php
Validation for post locking and post conflicts is only applied at save.
Post locking:
Post conflicts:
Fixes #142.
=> Add support for setting validation in 4.6-alpha

php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php
This fixes an issue whereby:
1. You change a featured image.
2. You hit Save & Publish.
3. You see the featured image refresh in the preview once saved.
The reason for the secondary refresh of the featured image is because I incorrectly used `WP_Customize_Setting::value()` as opposed to `WP_Customize_Setting::js_value()`. For postmeta containing post IDs for media controls like Featured Image, this is particularly important because all scalar postmeta (e.g. numbers and bools) get saved as strings (since a `meta_value` is a `TEXT` field). We implement a `js_value` to cast the underlying string attachment ID from a string to an integer for JS. Since I didn't do this, when the Customizer saves and it sends back the sanitized saved values to update in the JS models, any integer post IDs get …
=> Send values to JS via js_value(); use setting json method if available

php/class-customize-posts-plugin.php, php/class-wp-customize-posts.php, tests/php/test-class-customize-posts-plugin.php, tests/php/test-class-wp-customize-posts.php
If you are previewing a snapshot on the front-end and click the edit post link, you'll see that `map_meta_cap()` throws a few notices that are essentially complaining that `get_post_status_object` is not returning an object. This PR moves the `register_customize_draft` method into `Customize_Posts_Plugin` so the `customize-draft` `post_status` will alway be added; instead of only in the Customizer.
=> Make sure the customize-draft status is avialble to Snapshots & wp-admin

php/class-wp-customize-posts.php
This prevents the draft post from becoming considered as in conflict if a publish is attempted after a snapshot save, as the modified date is the initial test for whether a post has changed.
=> Do not update the modified date during customize-draft transition

php/class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-post-setting.php
=> Delete auto-draft and customize-draft status posts when saving a trash post_status

php/class-wp-customize-post-section.php, tests/php/test-class-wp-customize-post-section.php
This fixes an issue where sections disappear if an Editor user attempts to access the Customizer and change a post.
=> Use post type's edit_posts capability for sections instead of default

js/customize-featured-image.js, js/customize-page-template.js, js/customize-post-section.js, js/customize-posts.js
This implements a key performance improvement. When there are a lot of posts loaded in to the Customizer, and each one has a featured image, in `develop` right now you will see an Ajax request made to fetch the attachment data for each image in the console. This is very wasteful and hurts the server. By waiting to embed the controls until the section is expanded, we can ensure that the controls are only embedded once they are actually needed. This will greatly reduce the hit on the DOM at page load, and also reduce the Ajax requests made for the `MediaControl` instances
Remaining todos:
=> Defer embedding section contents until expanded

js/customize-post-section.js, php/class-wp-customize-post-setting.php
When a `post` setting is marked as invalid and the returned `WP_Error` includes a `setting_property` field, ensure that the corresponding control for this notification gets the notification displayed and gets focus when attempting to submit.
Depends on https://core.trac.wordpress.org/ticket/36944
=> Add support for setting-property control notifications and focusing

js/customize-post-section.js
I noticed an issue whereby I'd navigate to a post in the preview and expand its section. The “preview” 👀 link would properly disappear. However, as soon as I changed the post title the preview link would re-appear unexpectedly. I found that it was because of the selective refresh also sending `customized-posts` messages, but with only a subset of the data when a full refresh is done. So the solution is to just check if `data.queriedPostId` is undefined.
=> Prevent customized-posts messages sent via selective-refresh from effecting post-navigation state

php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
Add `IN` Meta query compare support. 
Using `$publish` flag to filter out posts which do not match meta query.
Add filter `customize_previewed_posts_for_query` for filtering previewed posts.
=> Improve meta query support

js/customize-post-section.js
Check for field_x in labels when registering post_type and use as lable for default fields
=> Allow post field control labels to be defined in register_post_type()

php/class-customize-posts-plugin.php
**Adds 'select2' to the dependency array for customize-posts-panel script.**
On a fresh WP install, the customizer was not fully loading due to a JS error.
Upon investigation, it was found that it was due to Select2 not being loaded into the page.
=> Include Select2 As a Dependency for Script

js/customize-posts.js, js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
Fixes a regression introduced in #196. The reason for the regression is that post settings now are added dynamically with JS instead of statically with PHP every time the preview loads. So now we can change the `focus-section` message to an `edit-post` message and re-use the new `ensurePosts` function to ensure that the section is present and focus on it.
=> Fix edit_post_link()

js/customize-posts.js
If a post section or control is autofocused, we need to ensure that this post gets fetched so that the section/control can be autofocused. This issue came to light when using Customize Posts with the [Customizer Browser History](https://github.com/xwp/wp-customizer-browser-history) plugin.
Fixes #204.
=> Ensure posts related to autofocused sections/controls

css/customize-posts.css, js/customize-post-date-control.js, php/class-wp-customize-post-date-control.php
This PR refines the date reset UI. Lesser UI is better UI :)
=> Feature/issue 56 Post Date Control Reset UI

js/customize-post-section.js, js/customize-posts-panel.js
This probably failed with the switch to embedding controls upon expanding a post section.
Fixes #209.
=> Fix selecting input for newly-inserted post's first control

css/customize-posts.css, js/customize-post-section.js, js/customize-post-status-control.js, js/customize-posts.js, php/class-customize-posts-plugin.php, php/class-customize-posts-support.php, php/class-wp-customize-featured-image-controller.php, php/class-wp-customize-post-date-control.php, php/class-wp-customize-post-setting.php, php/class-wp-customize-post-status-control.php, php/class-wp-customize-posts-panel.php, php/class-wp-customize-posts.php, tests/php/test-ajax-class-wp-customize-posts.php, tests/php/test-class-wp-customize-post-date-control.php, tests/php/test-class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-post-status-control.php, tests/php/test-class-wp-customize-posts.php
* Adds custom control template for post status control
* Introduces “Move to Trash” link that appears next to dropdown which appears when the status is not `trash`.
* Clicking the “Move to Trash” link sets the setting's `post_status` property to `trash` and then collapses the post section, to add a similar experience to clicking this same link on the edit post admin screen where clicking the link moves the user to the post list table. The collapse is done after a half-second delay to show the user that clicking the link just changes the dropdown, giving them a clue to restore the post by changing the status back to something other than `trash`.
* The post can be untrashed simply by re-expanding the section and changing the status to a non-trash status.
Fixes #172.
=> Improve UX for trashing posts

php/class-wp-customize-post-setting.php
The filter gets added if `$is_trashed` so this should be the condition for removal as well.
=> Ensure wp_insert_post_empty_content filter gets removed after trashing

customize-posts.php, php/class-customize-posts-plugin.php
We're currently not able to make use of translate.wordpress.org for translating the plugin. It [reports](https://translate.wordpress.org/locale/es-mx/default/wp-plugins/customize-posts):
> This plugin is not properly prepared for localization.
I thought that the `Text Domain` plugin meta could be empty since it is now assumed to be the slug, I thought, but I added it in https://github.com/xwp/wp-customize-posts/commit/421da210a44a1b6defd7e70055d42475bed5ab9d to try to fix the issue on translate.wordpress.org. However, that didn't fix it in 0.7.0. I also thought that `Domain Path` was optional, but maybe it isn't. 
Anyone have any specifics for what is missing?
=> Attempt to enable translating via translate.wordpress.org

php/class-customize-posts-plugin.php, php/class-wp-customize-featured-image-controller.php
@westonruter, 
Could you please review this pull request for Issue #132?
The new filter `add_posts_to_customize_loaded_components` adds `'posts'` to the array of components in the Customizer.
And `WP_Customize_Posts` is only instantiated if `'posts'` is still present.
So a later filter may remove `'posts'`, to disable it.
One issue I noticed is that if a filter does remove `'posts'`, it causes a fatal error:
```Notice: Undefined property: WP_Customize_Manager::$posts in /srv/www/wordpress-develop/src/wp-content/plugins/wp-customize-posts/php/class-customize-posts-plugin.php on line 179
Fatal error: Call to a member function add_support() on a non-object in /srv/www/wordpress-develop/src/wp-content/plugins/wp-customize-posts/php/class-customize-posts-plugin.php on line 179```
Removing the …
=> Issue #132 : Allow filtering to disable 'posts' component.

js/customize-page-template.js
See logic for when the Page Template control should be displayed here: https://github.com/xwp/wordpress-develop/blob/4.6.0/src/wp-admin/includes/meta-boxes.php#L820
=> Restrict page template control to just the page post type

js/customize-post-section.js
See https://core.trac.wordpress.org/ticket/37890#comment:2
=> Use notification.setting instead of notification.data.setting

php/class-customize-posts-plugin.php, tests/php/test-class-customize-posts-plugin.php
=> Add autofocus[section] param to Customize admin bar link when is_singular

php/class-customize-posts-plugin.php, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts.php
This fixes an issue in snapshots frontend preview where auto-draft posts previewed as published would get erroneously redirected from the preview URL to instead have a URL like `/-0001/11/30/` since the date is `0000-00-00` and the post_name is empty. This URL would then redirect to the homepage.
This also ensures that WordPress will be able to locate the customized post since the `post_name` may have been changed.
This PR also adds (for good measure) a `validate_file()` to the results of a `glob()`, and adds `sanitize_text_field()` for the input of post searching.
=> Ensure that preview urls are used as permalinks for customized posts

php/class-customize-posts-plugin.php
This should largely eliminate the need for #133 and it will fix a contributor's first hurdle when they clone the plugin from GitHub, activate it, and find it to be broken.
=> Use non-minified scripts and styles if plugin installed via git (submodule)

php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
=> Add support for including previewed changes in calls to get_pages()

php/class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-post-setting.php
Align with a core oddity of `WP_Post` that `post_author` is a `string` as opposed to an `int`. See https://core.trac.wordpress.org/ticket/22324
The `post_author` value will remain a `Number` in JavaScript and will not be casted to a `String`.
=> Make sure post_author is string in PHP but keep int in JS

php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
Even when there are no pages yet created, the Static Front Page should still get added because a page can be created _inside_ the customizer. If there are no pages created initially, then the section will be hidden via the `active_callback`.
Fixes #252.
=> Ensure that static front page constructs get registered with active callbacks

js/customize-post-section.js, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php
A better drag-and-drop UI needs to be developed for this (in core as well). For now, something is better than nothing. See #32.
Note that this introduces a new post-type support called “`ordering`” which can be used to enable _just_ the order field since the `page-attributes` field enables both the `post_parent` and `menu_order` controls.
Fixes #84.
=> Add rudimentary number-based menu_order field

php/class-wp-customize-posts.php, phpcs.ruleset.xml
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/685
=> Allow 'default' text domain

js/customize-post-section.js, js/customize-posts.js, php/class-wp-customize-posts.php
Continuation of #190.
Fixes #153.
=> Sync page changes to Static Front Page section controls; prevent same page from being used as both page for posts and page on front

js/customize-posts.js, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
Also add newly-created pages immediately to dropdown-pages controls and activate `static_front_page` section immediately.
=> Let static_front_page section be contextual instead of controls

js/customize-page-template.js, js/customize-post-section.js, php/class-wp-customize-posts.php
=> Improve support for page_for_posts by hiding page template and editor while showing notice

js/customize-post-editor-control.js
=> Ensure that section containing post editor control is expanded upon control expansion

css/customize-posts.css, js/customize-post-editor-control.js, js/customize-posts.js
=> Prevent editor from inadvertently closing with ESC; ensure TinyMCE toolbars hide when collapsed

js/customize-posts.js
/cc https://github.com/xwp/wp-customize-object-selector/pull/12
=> Rename createPost to startCreatePostFlow and editPost to startEditPostFlow

css/customize-posts.css, js/customize-nav-menus-posts-extensions.js, js/customize-posts.js, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
=> Integrate Customize Posts with Nav Menus

js/customize-nav-menus-posts-extensions.js, js/customize-posts.js
=> Improve nav menus integration

js/customize-posts.js
In Safari, but not other browsers, `new Date( "2016-09-23 14:57:10" )` is an *Invalid Date*. It turns out that including `T` delimiting the date from the time causes it to work in Safari, so this PR implements that.
=> Fix broken getCurrentTime() method in Safari 

composer.json, customize-posts.php, js/customize-post-editor-control.js, js/customize-posts.js, package.json, readme.md, readme.txt
=> Release 0.8.1

js/customize-post-date-control.js, js/customize-post-status-control.js, js/customize-posts.js
=> Fix browser incompatible way of parsing local datetime strings

composer.json, customize-posts.php, js/customize-post-date-control.js, js/customize-post-status-control.js, js/customize-posts.js, package.json, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php, readme.md, readme.txt, tests/php/test-class-wp-customize-posts-preview.php
=> Release 0.8.2

js/customize-post-section.js, js/customize-posts.js
Prevent the `section.params` other than `post_id` and `post_type` from being included in preview URL. Prevents URLs from being previewed that look like:
http://wp.example.com/?preview=true&p=6189&id=post%5Bpost%5D%5B6189%5D&panel=posts%5Bpost%5D&active=true&customizeAction=Customizing%2B%E2%96%B8%2BPosts&title=Hello%2BWorld&description=&priority=100&type=default&content=&instanceNumber=
The issue happened specifically when you clicked the post navigation link or if you jumped to a post via the select2 and the post was not visible in the preview:
=> Prevent extra section params from being passed along to previewUrl

php/class-wp-customize-posts-preview.php
Issue discussion https://github.com/xwp/wp-customize-posts/commit/0df94bb337fe091dd67ea9f4f6889dba6519ba4c#commitcomment-19463405
=> Return null if can not preview customize postmeta setting

js/customize-preview-posts.js, tests/php/test-class-wp-customize-posts.php
Depends on https://github.com/xwp/wordpress-develop/pull/161
=> Improve compatibility with Customize Changesets (née Transactions aka Snapshots)

php/class-wp-customize-posts.php, tests/php/test-class-customize-posts-plugin.php, tests/php/test-class-wp-customize-post-field-partial.php
Disable the new core UI for adding page stubs via the `dropdown-pages` controls since Customize Posts has its own UI that includes editing.
=> Recognize and handle dropdown-pages control in WP 4.7-alpha

php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-page-template-controller.php, tests/php/test-class-wp-customize-postmeta-setting.php
See https://core.trac.wordpress.org/ticket/38648
=> Restore edit_post_link() in WordPress 4.7

js/customize-nav-menus-posts-extensions.js, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
See https://core.trac.wordpress.org/ticket/38122
=> Disable polyfill for nav menu item loading/searching fix landing in 4.7

php/class-wp-customize-post-setting.php, php/class-wp-customize-postmeta-setting.php, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-post-setting.php, tests/php/test-class-wp-customize-postmeta-setting.php
Use dynamic capabilities that include the params embedded as keys, and then map the meta cap just in time.
See https://core.trac.wordpress.org/ticket/38672
=> Eliminate determination of user capability in setting constructor

js/customize-preview-posts.js
This was causing admin-ajax requests on the frontend from failing to get the customized state injected since the `allowAdminAjax` param was not passed.
=> Pass missing options param in wrapped isLinkPrewable function

php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php
Ensure that page/post stubs are included among the queried posts so that when the customizer loads these posts/pages their corresponding post sections will be pre-loaded. Also when saving, filter out post IDs from `nav_menus_created_posts` when there are corresponding `post` settings to prevent conflicts between saving the two.
=> Improve compat with posts & pages created as stubs in 4.7

php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-posts.php
Also allow plugins to explicitly opt-in for attachments in customizer.
Fixes #324.
=> Improve method for skipping attachments so no error in console appears

js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
See [#39098](https://core.trac.wordpress.org/ticket/39098) (Customize: Clicking on child elements of preview links fails to abort navigation to non-previewable links)
=> Handle edit post links that have child elements; remove need for data-customize-post-id attribute

js/customize-post-field-partial.js, js/customize-preview-featured-image.js, js/customize-preview-posts.js, php/class-wp-customize-featured-image-controller.php, php/class-wp-customize-posts-preview.php, php/theme-support/class-customize-posts-twenty-eleven-support.php, php/theme-support/class-customize-posts-twenty-fifteen-support.php, php/theme-support/class-customize-posts-twenty-seventeen-support.php, php/theme-support/class-customize-posts-twenty-sixteen-support.php, php/theme-support/class-customize-posts-twenty-ten-support.php, php/theme-support/class-customize-posts-twenty-thirteen-support.php, php/theme-support/class-customize-posts-twenty-twelve-support.php, tests/data/themes/dummy/functions.php
The changes are part of some experimentation I'm doing (along with JS Widgets) to enable Customize Posts to directly mutate Backbone models created from the WP-API JS client, with the aim of demonstrating patterns for how Customize Posts can be used to manage themes that are rendered purely with JS templates. As part of this I found that we need the partials to be smarter about when they decide that they need to do the fallback behavior of a full refresh. I've introduced the idea of a “fallback dependent selector” which is used to do a test on the document to see whether or not a refresh is warranted. Namely, this selector is intended to normally match the body class or post class that would reference a given post so that if neither the current singular preview or the current archive loop …
=> Improve logic for determining when to do fallback refresh for post field partials

php/class-edit-post-preview.php
See https://core.trac.wordpress.org/ticket/39610
=> Prevent warning when importing starter content including CPT posts

customize-posts.php
Removing reference to the now obsolete Customize Setting Validation plugin.
Fixes #323.
=> Update plugin description to remove reference to obsolete feature plugin

php/class-customize-posts-plugin.php, php/class-wp-customize-posts.php, tests/php/test-class-customize-posts-plugin.php, tests/php/test-class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts.php
=> Use auto-draft with late future date instead of customize-draft and clean auto-draft on changeset delete.

js/customize-posts-panel.js, php/class-wp-customize-posts.php
Fixes https://github.com/xwp/wp-customize-posts/issues/217
=> Show notification when a post a restored from trash

js/customize-posts-panel.js
**Issue:** When we type to select a post in post-select-lookup select2 input , it sends continuous ajax requests for each letter we type without any delay. Ideally the previous request should cancel each time a new request is sent and there should be at least some delay. This PR fixes that issue.
Example of Issue:
=> Stop continuous ajax requests in select2

.travis.yml, css/edit-post-preview-admin.css, css/edit-post-preview-customize.css, js/edit-post-preview-admin.js, js/edit-post-preview-customize.js, php/class-customize-posts-plugin.php, php/class-edit-post-preview.php, tests/php/test-ajax-class-wp-customize-posts.php
Fixes https://github.com/xwp/wp-customize-posts/issues/338
=> Remove sessionStorage and use changeset to save post editor screen data.

.travis.yml, css/edit-post-preview-admin.css, css/edit-post-preview-customize.css, customize-posts.php, js/customize-post-section.js, js/customize-posts-panel.js, js/customize-posts.js, js/edit-post-preview-admin.js, js/edit-post-preview-customize.js, php/class-customize-posts-plugin.php, php/class-edit-post-preview.php, php/class-wp-customize-posts.php, tests/php/test-ajax-class-wp-customize-posts.php, tests/php/test-class-customize-posts-plugin.php, tests/php/test-class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts.php
=> Release 0.8.6

.travis.yml, js/customize-deferred-partial.js, js/customize-post-field-partial.js, js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
Fixes https://wordpress.org/support/topic/no-support-for-page-on-front/
=> Fix post field partial from erroneously selecting nested post placements

php/theme-support/class-customize-posts-twenty-seventeen-support.php
Before:
After:
Patch upstreamed to theme in https://core.trac.wordpress.org/ticket/41557
=> Add fix for nested edit shortcuts in Twenty Seventeen front-page panels

php/class-customize-posts-plugin.php
This partially reverts #258.
The component can only be checked for being disabled when the Customizer is instantiated, but the postmeta controllers have to be instantiated outside the Customizer for integration with the edit post screen.
Fixes #359.
=> Fix syncing of post changes made in post preview customizer back to edit post screen

js/customize-post-section.js, php/class-wp-customize-posts.php
Depends on https://github.com/xwp/wordpress-develop/pull/260
See https://core.trac.wordpress.org/ticket/38794
=> Make use of section notifications API in WP 4.9 when available; otherwise polyfill

js/customize-post-section.js
=> Update wrapper around notifications.add for new params accepted in 4.9

composer.json, customize-posts.php, package.json, php/class-wp-customize-posts.php, readme.md, readme.txt, tests/php/test-class-wp-customize-postmeta-controller.php, tests/php/test-class-wp-customize-posts.php
When a scheduled changeset publishes via WP Cron, the Customizer will bootstrap after the `init` action. In the course of normal Customizer bootstrapping, it happens at the `plugins_loaded` action. Because postmeta currently is registered at the `init` action, this means that the postmeta will not get registered during WP Cron because the Customizer will bootstrap after `init`.
This is also a problem for changesets that get published via WP-CLI, since `init` also is done before `wp post update $changeset_post_id --post_status=publish`.
In the Customizer the way to reproduce the problem is:
1. Open Customizer
2. Open a post to edit.
3. Change the post title
4. Change the featured image
5. Schedule the changes to go live.
6. At the scheduled time, the post title change is published whereas …
=> Fix saving of postmeta in scheduled changesets
