xwp/wp-customize-posts

.travis.yml, js/customize-preview-posts.js, readme.md, readme.txt
=> Use wp.customize.preview in Preview since now available

css/edit-post-preview-customize.css, js/customize-post-section.js, js/edit-post-preview-admin.js, js/edit-post-preview-customize.js, php/class-customize-posts-plugin.php, php/class-edit-post-preview.php, readme.md, readme.txt
See demo: https://youtu.be/Q62nav1k4gY
Fixes #3.
=> Implement post preview in Customizer

css/customize-posts.css
=> Ensure thickbox has high enough z-index to be seen

js/customize-post-field-partial.js, js/customize-post-section.js, js/customize-preview-posts.js, js/edit-post-preview-admin.js, php/class-wp-customize-post-field-partial.php
=> Add post excerpt control

js/customize-preview-posts.js, php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
=> Export post and postmeta settings during selective refresh requests

.dev-lib, js/customize-dynamic-control.js, js/customize-post-field-partial.js, js/customize-post-section.js, js/customize-posts.js, js/customize-preview-posts.js, js/edit-post-preview-admin.js, php/class-wp-customize-dynamic-control.php, php/class-wp-customize-post-discussion-fields-control.php, php/class-wp-customize-post-field-partial.php, php/class-wp-customize-post-setting.php, php/class-wp-customize-posts-preview.php, php/class-wp-customize-posts.php, tests/php/test-class-wp-customize-page-template-controller.php, tests/php/test-class-wp-customize-post-field-partial.php, tests/php/test-class-wp-customize-posts-preview.php
=> Discussion controls

js/customize-preview-featured-image.js, js/edit-post-preview-admin-featured-image.js, php/class-wp-customize-featured-image-controller.php
=> Fix featured image in WP 4.5

js/customize-post-field-partial.js, js/customize-preview-posts.js, php/class-wp-customize-post-field-partial.php, php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
Fixes issue in Twenty Sixteen with one of the avatars not getting updated.
=> Add avatar post field partial placements

css/customize-posts.css
@valendesigns Here it is.
Fixes #44
=> Show Collapse Arrow when pane is closed

readme.md, readme.txt
=> Fix readme s/the Customize/the Customizer/

php/class-wp-customize-posts-preview.php
=> Move comments_open and pings_open filters

js/customize-posts.js
=> Fix purgeTrash by setting active to false

php/class-customize-posts-plugin.php
See https://core.trac.wordpress.org/ticket/36521
Now committed to `trunk` in https://core.trac.wordpress.org/changeset/37701
=> Improve feature detection for including customize-controls patched for trac-36521

css/customize-posts.css
=> Fix post control ui

php/plugin-support/class-customize-posts-direct-manipulation-support.php
See https://github.com/Automattic/customize-direct-manipulation/issues/22
Depends on https://github.com/Automattic/customize-direct-manipulation/pull/31
=> Disable edit-post-links module in customize-direct-manipulation plugin

css/customize-posts.css
See https://core.trac.wordpress.org/ticket/37527
=> Remove underline from time-info-handle in 4.7-alpha

js/customize-posts-panel.js, php/class-wp-customize-posts.php
=> Eliminate 'Jump to Post' in favor of re-using search_items label

css/customize-posts.css, js/customize-posts-panel.js
Implements `todo`, inspired by code in https://core.trac.wordpress.org/changeset/38436
=> Use flexbox for post selection lookup select2 and add button

js/edit-post-preview-admin.js
=> Make sure that menu_order is synced between edit post screen with post preview customizer

php/class-customize-posts-plugin.php, php/class-edit-post-preview.php
=> Prevent loading postmeta controllers if posts component is disabled

css/customize-posts.css, js/customize-posts-panel.js, js/customize-posts.js, php/class-wp-customize-posts.php
=> Include create/edit buttons with dropdown-pages controls

php/class-wp-customize-posts.php
Fixes defect in #272.
See #268.
=> Ensure nav_menu_item setting IDs are recognized in requests to fetch settings

js/customize-posts-panel.js
Fixes regression introduced in #284
=> Remaining straggler createPost() to startCreatePostFlow()

js/customize-nav-menus-posts-extensions.js, js/customize-posts.js, php/class-customize-posts-plugin.php, php/class-wp-customize-posts.php
=> Insert full posts instead of stubs via nav menus

php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
=> Prevent post preview from applying when viewing page_for_posts with preview=true

php/class-wp-customize-posts-preview.php, tests/php/test-class-wp-customize-posts-preview.php
Added `$setting` in `customize_previewed_postmeta_rows` filter.
Added new filter `customize_previewed_postmeta_rows_{$setting->post_meta}`
=> Update customize preview post meta rows filter

js/customize-preview-featured-image.js, php/class-wp-customize-featured-image-controller.php, tests/php/test-class-wp-customize-featured-image-controller.php
=> Differentiate featured image partials on index templates for separate posts

js/customize-post-section.js
=> Focus on specific field that have conflict

js/customize-posts.js
=> Post section `customizeAction` template var from post_type labels object

js/customize-deferred-partial.js
=> Fix selector for detecting presence of existing edit shortcut
